package com.bookreaderai.backend.controller;

import com.bookreaderai.backend.dto.RagAskRequest;
import com.bookreaderai.backend.dto.RagQuizRequest;
import com.bookreaderai.backend.service.RagQaService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * REST endpoints that expose Retrieval-Augmented Q&A and quiz generation.
 */
@RestController
@RequestMapping("/rag")
@RequiredArgsConstructor
public class RagController {

    private final RagQaService ragQaService;

    /**
     * Ask a question about a particular book.
     *
     * @return plain-text answer generated by the LLM.
     */
    @PostMapping(value = "/ask", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<String> ask(@RequestBody RagAskRequest req,
            @RequestParam(defaultValue = "5") int topK) {

        String answer = ragQaService.answerQuestion(req.bookName(), req.question(), topK);
        return ResponseEntity.ok(answer);
    }

    @PostMapping(value = "/quiz", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<String> quiz(@RequestBody RagQuizRequest req,
            @RequestParam(defaultValue = "8") int topK) {

        String quiz = ragQaService.generateQuiz(req.bookName(), req.instruction(), topK);
        return ResponseEntity.ok(quiz);
    }

    @PostMapping(value = "/structured-quiz", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> structuredQuiz(@RequestBody RagQuizRequest req,
            @RequestParam(defaultValue = "8") int topK) {

        String quizJson = ragQaService.generateStructuredQuiz(req.bookName(), req.instruction(), topK);
        return ResponseEntity.ok(quizJson);
    }
}
